CREATE TABLE IF NOT EXISTS Roles (
  Id INTEGER PRIMARY KEY,
  Name TEXT NOT NULL,
  GuildId INTEGER NOT NULL,
  ParentId INTEGER NOT NULL,
  FOREIGN KEY (GuildId) REFERENCES Guilds(Id),
  FOREIGN KEY (ParentId) REFERENCES Roles(Id)
)